add workflow id param to destroy-environment command

diff --git a/.circleci/config_sample.yml b/.circleci/config_sample.yml
--- a/.circleci/config_sample.yml
+++ b/.circleci/config_sample.yml
@@ -4,8 +4,7 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      workflow-id:
-        type: string
+      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
@@ -16,8 +15,8 @@ commands:
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
-    # parameters:
-    # Add parameter here
+    parameters:
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
@@ -32,7 +31,7 @@ commands:
             #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
-
+            
 jobs:
   build-frontend:
     docker:
@@ -42,15 +41,13 @@ jobs:
       - restore_cache:
           keys: [frontend-build]
       - run:
-          name: Build Frontend
+          name: Build front-end
           command: |
-            cd frontend
-            npm install
-            npm run build
+            # Your code here
+            exit 1
       - save_cache:
+          paths: [frontend/node_modules]
           key: frontend-build
-          paths:
-            - src/node_modules
 
   build-backend:
     docker:
@@ -60,67 +57,51 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: Backend build
+          name: Back-end build
           command: |
-            # Your code here
-            exit 1
+             # Your code here
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-          key: frontend-build
-      - run:
-        name: Test Frontend
-        command: |
-          npm run test
-
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+                
   test-backend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-          key: backend-build
-      - run:
-          name: Test Backend
-          command: |
-            npm run test
-
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+            
   scan-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-          key: frontend-build
-      - run:
-        name: Scan Frontend
-        command: |
-          npm run lint
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
 
   scan-backend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-          key: backend-build
-      - run:
-        name: Scan Backend
-        command: |
-          npm run lint
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
 
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli # Docker image here that supports AWS CLI
+      # Docker image here that supports AWS CLI
     steps:
-      - checkout
+      # Checkout code from git
       - run:
           name: Ensure back-end infrastructure exists
           command: |
@@ -140,7 +121,7 @@ jobs:
               # --parameter-overrides ID="your workflow id"  
               exit 1
       - run:
-          name: Add Backend IP To Ansible Inventory
+          name: Add back-end ip to ansible inventory
           command: |
             # Your code here
             exit 1
@@ -148,7 +129,7 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     docker:
@@ -158,7 +139,7 @@ jobs:
       # Add ssh keys with fingerprint
       # attach workspace
       - run:
-          name: Install Dependencies
+          name: Install dependencies
           command: |
             # Your code here
             exit 1
@@ -167,7 +148,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
@@ -184,7 +165,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-      # Here's where you will add some code to rollback on failure
+     # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
@@ -205,8 +186,8 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
-
+      # Here's where you will add some code to rollback on failure      
+                    
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
@@ -222,11 +203,11 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
-      # Lightweight Docker image
+      # Lightweight Docker image 
     steps:
       # Checkout code from git
       - run:
@@ -245,7 +226,7 @@ jobs:
           name: Frontend smoke test.
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
@@ -260,26 +241,27 @@ jobs:
           name: Update cloudfront distribution
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
 cleanup:
-  docker:
-    # Docker image here
-  steps:
-    # Checkout code from git
-    - run:
-        name: Get old stack workflow id
-        command: |
-          # your code here
-          export OldWorkflowID="the id here"
-          export STACKS=[] #put the list of stacks here
-    - run:
-        name: Remove old stacks and files
-        command: |
-          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-          then
+    docker:
+      # Docker image here
+    steps:
+      # Checkout code from git
+      - run:
+          name: Get old stack workflow id
+          command: |
             # your code here
-          fi
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
+            
 
 workflows:
   default:
